### PR TITLE
Add podspec to repo

### PR DESCRIPTION
**Pull request by kerrmarin**
This should enable support for cocoapods.

I've tested this with this file locally in my checked out fork and I was able to add the repo as a local pod.

I will note that there is already a pod called [ASCollectionView](https://github.com/abdullahselek/ASCollectionView) so I suspect you'll have to change the name in the podspec to something unique before publishing. I've not published it myself for obvious reasons...

Let me know if I can help any other way to get this merged in and released :)

### CODE REVIEW

**Comment by kerrmarin** [comment]
@apptekstudios any feedback on this?

**Comment by apptekstudios** [comment]
@kerrmarin Thanks for making the podspec! I haven't been able to get it to pass a `pod spec lint` and haven't had time to dig further. Do you have any experience in getting this to work?

I've actually intentionally avoided adding cocoapods support to date, as anyone building for iOS13 should be able to use SPM. Additionally it adds many extra steps to releasing new versions. I'd be curious to hear your use case for needing cocoapods?

**Comment by kerrmarin** [comment]
Hey @apptekstudios, apologies for the late reply. I've pushed a change to the podspec which on my machine does pass linting. Let me know if you still have an error and I'll look into it, or if you want I can add an action/step on travis to lint the spec on every commit.

We have an existing project that already uses cocoapods and we don't want to maintain two different dependency management systems. If you're reluctant to add support for cocoapods another option I can suggest is that I maintain a fork of the repo that simply keeps up to date with this repo and I push releases to trunk from. Happy to add you as an owner/maintainer to that spec so you can push new releases if you want.

**Comment by apptekstudios** [comment]
Thanks @kerrmarin! 

If you have experience with getting travis to lint the podspec, that would be great. I'll merge this now but would appreciate another PR if you get a chance to set that up :)

**Pull request merged**
